#!/usr/bin/env bash

##
# This script is for batch converting tree markdown files.
# It looks for *.md files in directory ./markdown, run md2html with each file as an argument
# and then saves the result as *.html files into directory ./html
# Run example:
# ./utils/update_html_files
##

fcnt=0
while IFS= read -r -d '' file
do
	fcnt=$((fcnt + 1))
done < <(find markdown/ -maxdepth 1 -type f -name "*.md" -print0)

fnum=1
while IFS= read -r -d '' file
do
	printf "[%2d/%2d] Processing %s\n" "$fnum" "$fcnt" "$file"
	fname="$(basename -s ".md" "$file")"
	if ! utils/md2html "markdown/${fname}.md" > "html/${fname}.html"; then
		exit 1
	fi
	fnum=$((fnum + 1))
done < <(find markdown/ -maxdepth 1 -type f -name "*.md" -print0)

echo "Done!"

exit 0

